import Foundation
import DHCore

public enum ElectricalNodeKind:String,Codable,Sendable { case batteryPositive, batteryNegative, fuse, relay, splice, ground, load, switchNode }
public struct ElectricalNode:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var key:String; public var kind:ElectricalNodeKind; public var voltage:Double }
public struct ElectricalEdge:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var from:EntityID; public var to:EntityID; public var resistanceOhm:Double; public var closed:Bool; public var fuseRatingA:Double? }
public struct ElectricalTopology:Codable,Sendable,Equatable {
 public var nodes:[ElectricalNode]; public var edges:[ElectricalEdge]
 public func node(_ key:String)->ElectricalNode? { nodes.first{$0.key==key} }
 public func starterPathResistance()->Double { edges.filter{$0.closed}.reduce(0){$0+$1.resistanceOhm} }
 public static func kingmaker()->Self { let bp=ElectricalNode(id:UUID(),key:"BATT+",kind:.batteryPositive,voltage:12.6), bn=ElectricalNode(id:UUID(),key:"BATT-",kind:.batteryNegative,voltage:0), fuse=ElectricalNode(id:UUID(),key:"FUSE-START",kind:.fuse,voltage:12.6), relay=ElectricalNode(id:UUID(),key:"RELAY-START",kind:.relay,voltage:12.6), starter=ElectricalNode(id:UUID(),key:"STARTER",kind:.load,voltage:0), ground=ElectricalNode(id:UUID(),key:"G101",kind:.ground,voltage:0); return .init(nodes:[bp,bn,fuse,relay,starter,ground],edges:[.init(id:UUID(),from:bp.id,to:fuse.id,resistanceOhm:0.002,closed:true,fuseRatingA:400),.init(id:UUID(),from:fuse.id,to:relay.id,resistanceOhm:0.003,closed:true,fuseRatingA:nil),.init(id:UUID(),from:relay.id,to:starter.id,resistanceOhm:0.006,closed:true,fuseRatingA:nil),.init(id:UUID(),from:starter.id,to:ground.id,resistanceOhm:0.045,closed:true,fuseRatingA:nil),.init(id:UUID(),from:ground.id,to:bn.id,resistanceOhm:0.006,closed:true,fuseRatingA:nil)]) }
}

public enum FluidNodeKind:String,Codable,Sendable { case tank, pump, filter, rail, engine, radiator, thermostat, reservoir, hose }
public struct FluidNode:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var key:String; public var kind:FluidNodeKind; public var quantity:Double; public var pressureKPa:Double; public var temperatureC:Double }
public struct FluidEdge:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var from:EntityID; public var to:EntityID; public var restriction:Double; public var leakRate:Double }
public struct FluidTopology:Codable,Sendable,Equatable { public var nodes:[FluidNode]; public var edges:[FluidEdge]; public mutating func step(_ dt:Double){ for i in edges.indices where edges[i].leakRate > 0 { if let n=nodes.firstIndex(where:{$0.id==edges[i].from}) { nodes[n].quantity=max(0,nodes[n].quantity-edges[i].leakRate*dt) } } } }
public enum KingmakerFluidNetworks {
 public static func fuel(liters:Double=0)->FluidTopology { let tank=FluidNode(id:UUID(),key:"FUEL-TANK",kind:.tank,quantity:liters,pressureKPa:0,temperatureC:20), pump=FluidNode(id:UUID(),key:"FUEL-PUMP",kind:.pump,quantity:0,pressureKPa:400,temperatureC:20), filter=FluidNode(id:UUID(),key:"FUEL-FILTER",kind:.filter,quantity:0,pressureKPa:380,temperatureC:20), rail=FluidNode(id:UUID(),key:"FUEL-RAIL",kind:.rail,quantity:0,pressureKPa:350,temperatureC:30); return .init(nodes:[tank,pump,filter,rail],edges:[.init(id:UUID(),from:tank.id,to:pump.id,restriction:0.05,leakRate:0),.init(id:UUID(),from:pump.id,to:filter.id,restriction:0.08,leakRate:0),.init(id:UUID(),from:filter.id,to:rail.id,restriction:0.04,leakRate:0)]) }
 public static func cooling()->FluidTopology { let engine=FluidNode(id:UUID(),key:"ENGINE-JACKET",kind:.engine,quantity:6,pressureKPa:110,temperatureC:20), thermostat=FluidNode(id:UUID(),key:"THERMOSTAT",kind:.thermostat,quantity:0.2,pressureKPa:105,temperatureC:20), radiator=FluidNode(id:UUID(),key:"RADIATOR",kind:.radiator,quantity:5,pressureKPa:100,temperatureC:20), reservoir=FluidNode(id:UUID(),key:"RESERVOIR",kind:.reservoir,quantity:1,pressureKPa:100,temperatureC:20); return .init(nodes:[engine,thermostat,radiator,reservoir],edges:[.init(id:UUID(),from:engine.id,to:thermostat.id,restriction:0.1,leakRate:0),.init(id:UUID(),from:thermostat.id,to:radiator.id,restriction:0.08,leakRate:0),.init(id:UUID(),from:radiator.id,to:engine.id,restriction:0.07,leakRate:0),.init(id:UUID(),from:radiator.id,to:reservoir.id,restriction:0.2,leakRate:0)]) }
}

public struct TransmissionState:Codable,Sendable,Equatable { public var ratios:[Double] = [2.97,2.07,1.43,1.00,0.84,0.56]; public var reverseRatio=2.90; public var selectedGear=1; public var clutchEngagement=1.0; public var finalDrive=3.73; public func activeRatio()->Double { selectedGear == 0 ? 0 : (selectedGear < 0 ? -reverseRatio : ratios[max(0,min(ratios.count-1,selectedGear-1))]) * finalDrive * max(0,min(1,clutchEngagement)) } }
public struct WheelDynamics:Codable,Sendable,Equatable { public var wheelOmega=0.0; public var slipRatio=0.0; public mutating func step(vehicleSpeed:Double,driveTorque:Double,radius:Double,dt:Double){ let surface=max(0.1,abs(vehicleSpeed)); wheelOmega += driveTorque/2.2*dt; slipRatio=(wheelOmega*radius-vehicleSpeed)/surface; wheelOmega *= 0.995 } }
public enum CollisionZone:String,Codable,CaseIterable,Sendable { case frontLeft,frontRight,rearLeft,rearRight,frontCenter,rearCenter,leftSide,rightSide,roof,floor }
public struct BodyDamageState:Codable,Sendable,Equatable { public var deformation:[CollisionZone:Double]=Dictionary(uniqueKeysWithValues:CollisionZone.allCases.map{($0,0)}); public mutating func apply(zone:CollisionZone,energyJ:Double){deformation[zone,default:0]=min(1,deformation[zone,default:0]+energyJ/900_000)} }
public struct CargoItem:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var name:String; public var massKg:Double; public var quantity:Int }
public struct CargoHold:Codable,Sendable,Equatable { public var baseVehicleMassKg=1850.0; public var items:[CargoItem]=[]; public var cargoMassKg:Double { items.reduce(0){$0+$1.massKg*Double($1.quantity)} }; public var totalMassKg:Double { baseVehicleMassKg+cargoMassKg } }
