import Foundation
import DHCore
public enum ComponentCondition: String, Codable, Sendable { case missing, seized, failed, poor, serviceable, good, restored }
public enum KingmakerSystem: String, Codable, CaseIterable, Sendable { case engine, induction, cooling, lubrication, fuel, ignition, electrical, transmission, driveline, differential, suspension, steering, brakes, wheelsTires, chassis, body, aero, lighting, armor, survival }
public struct VehicleComponent: Identifiable, Codable, Sendable, Equatable { public let id: EntityID; public var name: String; public var system: KingmakerSystem; public var condition: ComponentCondition; public var wear: Double }
public struct KingmakerState: Codable, Sendable, Equatable { public let id: EntityID; public var name = "XR-13 Kingmaker"; public var components:[VehicleComponent]; public var fuelLiters:Double; public var batterySOC:Double; public var fuelPressureKPa:Double=0; public var oilPressureKPa:Double=0; public var coolantC:Double=20; public var engineRunning:Bool
 public func hasViable(_ system:KingmakerSystem)->Bool { components.contains{$0.system==system && ![.missing,.seized,.failed].contains($0.condition)} }
 public var visualStates: [KingmakerComponentVisualState] { components.map { KingmakerComponentVisualState(componentID: $0.id.uuidString, condition: $0.condition) } }
 public var canCrank:Bool { batterySOC > 0.15 && hasViable(.engine) && hasViable(.electrical) }
 public var canStart:Bool { canCrank && fuelLiters > 0.5 && fuelPressureKPa > 150 && hasViable(.fuel) && hasViable(.ignition) && hasViable(.lubrication) && hasViable(.cooling) }
 public mutating func crank(seconds:Double)->Bool { guard canCrank else{return false}; batterySOC=max(0,batterySOC-0.012*seconds); if canStart { engineRunning=true; oilPressureKPa=300; return true }; return false }
 public mutating func simulate(seconds:Double){ guard engineRunning else{return}; fuelLiters=max(0,fuelLiters-0.0015*seconds); batterySOC=min(1,batterySOC+0.002*seconds); coolantC += hasViable(.cooling) ? 0.03*seconds : 1.2*seconds; if fuelLiters<=0 || coolantC>125 { engineRunning=false } }
 public static func derelict(id:EntityID=UUID())->Self { let essentials:[(String,KingmakerSystem,ComponentCondition)] = [("429-pattern big-block core",.engine,.seized),("Roots supercharger assembly",.induction,.poor),("Radiator",.cooling,.failed),("Oil pump",.lubrication,.poor),("Fuel pump",.fuel,.failed),("Ignition module",.ignition,.poor),("Battery/charging harness",.electrical,.failed),("Six-speed gearbox",.transmission,.serviceable),("Limited-slip differential",.differential,.poor),("Front suspension",.suspension,.poor),("Four-wheel brakes",.brakes,.failed),("Wheels and tires",.wheelsTires,.poor),("Fastback chassis",.chassis,.serviceable),("Kingmaker body",.body,.poor)]; return .init(id:id,components:essentials.map{.init(id:UUID(),name:$0.0,system:$0.1,condition:$0.2,wear:0.7)},fuelLiters:0,batterySOC:0,engineRunning:false) }
}
