import Foundation
import DHCore
public enum BlackridgeSite: String, Codable, CaseIterable, Sendable { case kingmakerGarage, truckStop, scrapyard, interstate, ruinedTown, mineComplex, railYard, fuelDepot, quarry, forestRoads, farms, substation, paradise }
public enum Faction:String,Codable,CaseIterable,Sendable { case highwayPatrol, refineryHouses, railUnion, motorTribes, restorationists, childrenOfBurn, homesteads, combine }
public struct SettlementEconomy: Codable, Sendable, Equatable { public var food:Double; public var water:Double; public var fuel:Double; public var medicine:Double; public var ammunition:Double; public var machinery:Double; public var electricity:Double; public mutating func tick(){ food=max(0,food-0.01); water=max(0,water-0.015); electricity=max(0,electricity-0.005) } }
public struct WorldCell:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var x:Int; public var y:Int; public var loaded:Bool; public var sites:Set<BlackridgeSite> }
public struct Convoy:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var faction:Faction; public var cargoFuel:Double; public var destination:BlackridgeSite; public var intact:Bool=true }
public struct BlackridgeWorld: Codable, Sendable, Equatable { public var discovered:Set<BlackridgeSite> = []; public var economy = SettlementEconomy(food:100,water:100,fuel:60,medicine:25,ammunition:20,machinery:40,electricity:50); public var cells:[WorldCell]=[]; public var convoys:[Convoy]=[]; public mutating func tick(){economy.tick()}; public mutating func resolve(_ convoyID:EntityID,arrived:Bool){ guard let i=convoys.firstIndex(where:{$0.id==convoyID}) else{return}; convoys[i].intact=arrived; if arrived {economy.fuel += convoys[i].cargoFuel} } }

public struct FactionLogistics:Codable,Sendable,Equatable { public var stock:[Faction:Double] = Dictionary(uniqueKeysWithValues:Faction.allCases.map{($0,50)}); public var reputation:[Faction:Double] = Dictionary(uniqueKeysWithValues:Faction.allCases.map{($0,0)}); public mutating func deliver(faction:Faction,amount:Double){stock[faction,default:0]+=amount}; public mutating func disrupt(faction:Faction,amount:Double){stock[faction,default:0]=max(0,stock[faction,default:0]-amount); reputation[faction,default:0]-=min(10,amount/10)} }