import Foundation
import DHCore
public enum RoadSurface:String,Codable,Sendable { case asphalt, crackedAsphalt, gravel, dirt, mud, sand, flooded }
public enum WeatherKind:String,Codable,Sendable { case clear, overcast, rain, storm, dust, fog, snow }
public struct WeatherState:Codable,Sendable,Equatable { public var kind:WeatherKind = .clear; public var precipitation=0.0; public var temperatureC=24.0; public var windMPS=2.0; public func gripMultiplier(surface:RoadSurface)->Double { let base:[RoadSurface:Double]=[.asphalt:1,.crackedAsphalt:0.9,.gravel:0.72,.dirt:0.66,.mud:0.45,.sand:0.52,.flooded:0.35]; return (base[surface] ?? 0.7) * (precipitation > 0.2 ? 0.82:1) } }
public struct RouteNode:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var x:Int; public var y:Int }
public struct RouteEdge:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var from:EntityID; public var to:EntityID; public var distance:Double; public var danger:Double; public var surface:RoadSurface }
public struct RouteGraph:Codable,Sendable,Equatable { public var nodes:[RouteNode]; public var edges:[RouteEdge]; public func route(from:EntityID,to:EntityID)->[EntityID] { guard from != to else{return [from]}; var q:[EntityID]=[from], prev:[EntityID:EntityID]=[:], seen:Set<EntityID>=[from]; while !q.isEmpty { let n=q.removeFirst(); for e in edges where e.from==n || e.to==n { let m=e.from==n ? e.to:e.from; if !seen.contains(m){seen.insert(m);prev[m]=n;if m==to { var p=[to]; var c=to; while let x=prev[c]{p.append(x);c=x}; return p.reversed() };q.append(m)} } }; return [] } }
public enum Commodity:String,Codable,CaseIterable,Sendable { case food,water,fuel,medicine,ammunition,machinery,electricity,scrap }
public struct ProductionRecipe:Codable,Sendable,Equatable { public var inputs:[Commodity:Double]; public var outputs:[Commodity:Double] }
public struct ProductionSite:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var name:String; public var inventory:[Commodity:Double]; public var recipe:ProductionRecipe; public var efficiency:Double; public mutating func tick(){ guard recipe.inputs.allSatisfy({inventory[$0.key,default:0] >= $0.value}) else{return}; for (k,v) in recipe.inputs{inventory[k,default:0]-=v}; for(k,v) in recipe.outputs{inventory[k,default:0]+=v*efficiency} } }

public enum DeadHighwayRegion:String,Codable,CaseIterable,Sendable { case blacktop, ashCounty, barrens, deadMetro, ironValley, greenCountry, glow, saltFlats, redBasin, divide, floodlands, lastHighway }
public struct RegionProfile:Codable,Sendable,Equatable { public var region:DeadHighwayRegion; public var climate:String; public var primaryIndustry:String; public var hazard:String; public var roadGrip:Double }
public enum ContinentAtlas { public static let regions:[RegionProfile] = [
.init(region:.blacktop,climate:"arid highway",primaryIndustry:"trade",hazard:"raiders",roadGrip:0.92),.init(region:.ashCounty,climate:"wet industrial",primaryIndustry:"coal",hazard:"fires",roadGrip:0.78),.init(region:.barrens,climate:"desert",primaryIndustry:"salvage",hazard:"heat",roadGrip:0.70),.init(region:.deadMetro,climate:"urban",primaryIndustry:"salvage",hazard:"collapse",roadGrip:0.68),.init(region:.ironValley,climate:"temperate",primaryIndustry:"steel",hazard:"industrial",roadGrip:0.82),.init(region:.greenCountry,climate:"forest",primaryIndustry:"agriculture",hazard:"mud",roadGrip:0.72),.init(region:.glow,climate:"exclusion",primaryIndustry:"rare salvage",hazard:"radiation",roadGrip:0.62),.init(region:.saltFlats,climate:"dry",primaryIndustry:"racing",hazard:"speed",roadGrip:0.88),.init(region:.redBasin,climate:"hot",primaryIndustry:"petroleum",hazard:"fire",roadGrip:0.80),.init(region:.divide,climate:"mountain",primaryIndustry:"mining",hazard:"rockfall",roadGrip:0.66),.init(region:.floodlands,climate:"marsh",primaryIndustry:"fishing",hazard:"flood",roadGrip:0.48),.init(region:.lastHighway,climate:"unknown",primaryIndustry:"unknown",hazard:"unknown",roadGrip:0.75)] }
