import Foundation
import DHCore
import DHCharacter
import DHFleet

public enum FireMode:String,Codable,Sendable { case single,burst,automatic }
public struct BallisticWeapon:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var name:String; public var muzzleVelocity:Double; public var baseDamage:Double; public var magazine:Int; public var ammo:Int; public var accuracy:Double; public var fireMode:FireMode; public init(id:EntityID=UUID(),name:String,muzzleVelocity:Double,baseDamage:Double,magazine:Int,ammo:Int,accuracy:Double,fireMode:FireMode = .single){self.id=id;self.name=name;self.muzzleVelocity=muzzleVelocity;self.baseDamage=baseDamage;self.magazine=magazine;self.ammo=ammo;self.accuracy=accuracy;self.fireMode=fireMode} }
public struct CombatantState:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var health:Double; public var armor:Double; public var suppression:Double; public var cover:Double; public init(id:EntityID=UUID(),health:Double=100,armor:Double=0,cover:Double=0){self.id=id;self.health=health;self.armor=armor;self.suppression=0;self.cover=cover} }
public struct AttackResult:Codable,Sendable,Equatable { public var hitChance:Double; public var damage:Double; public var penetrated:Bool }
public enum AdvancedCombatResolver { public static func resolve(weapon:BallisticWeapon,skill:Int,distanceM:Double,target:CombatantState)->AttackResult { let rangePenalty=max(0,distanceM/120)*0.25; let chance=max(0.03,min(0.97,weapon.accuracy+Double(skill)*0.035-rangePenalty-target.cover-target.suppression*0.1)); let energy=0.5*0.008*weapon.muzzleVelocity*weapon.muzzleVelocity; let penetration=energy/1000 > target.armor; let damage=penetration ? weapon.baseDamage*(1-target.armor*0.03):weapon.baseDamage*0.2; return .init(hitChance:chance,damage:max(0,damage),penetrated:penetration) } }
public struct VehicleWeaponMount:Identifiable,Codable,Sendable,Equatable { public let id:EntityID; public var name:String; public var ammunition:Int; public var arcDegrees:Double; public var condition:Double; public init(id:EntityID=UUID(),name:String,ammunition:Int,arcDegrees:Double,condition:Double=1){self.id=id;self.name=name;self.ammunition=ammunition;self.arcDegrees=arcDegrees;self.condition=condition} }
public enum VehicleCombatResolver { public static func fire(_ mount:inout VehicleWeaponMount)->Bool { guard mount.ammunition>0,mount.condition>0.15 else{return false};mount.ammunition-=1;mount.condition=max(0,mount.condition-0.001);return true }; public static func ramDamage(attackerMass:Double,targetMass:Double,relativeSpeed:Double)->(attacker:Double,target:Double){let e=0.5*(attackerMass*targetMass/(attackerMass+targetMass))*relativeSpeed*relativeSpeed;return(e/100000*0.35,e/100000*0.65)} }
